### ISSUE TITLE
Code quality improvements

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1633]
## 📚 Documentation

Need to touch on
* [x] `pre-commit` #1598 
* [x] Linting in CI #1645 
* [x] Move to squash and merge - done in Github settings
* [x] `good-first-issue` - mentioned in new `CONTRIBUTING.md` more prominently
* [x] Revamp issue and workflow template and clarify `CONTRIBUTING.md` https://github.com/pytorch/serve/pull/1649
* [ ] Handler updates
  * [ ] Debugging standalone handlers https://github.com/pytorch/serve/pull/1661 - PR Ready
  * [ ] Modularity #1631 - PR Ready #1664
* [ ] Refactor tests
  * [ ]  Prereq: Refactor tests into one directory - I want to run `pytest .` and have it just work not need any assumptions about mar files generated offline or stubs generated in some other script. We should use `conftest.py` for everything setup related 
  * [ ] Flaky test removal #1586 
  * [ ] Test time reduction #1637 
* [ ] Test coverage #1636 #1665 
* [ ] docstrings
* [x] Types? #1419 
* [ ] Github bot to run benchmarks, notify on regression in benchmarks, auto assignment to review
